"""Upgrade text columns to LONGTEXT for MySQL base64 support

Revision ID: 0a01c5063dca
Revises: 
Create Date: 2026-04-08 03:23:08.334526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a01c5063dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.alter_column('hero_image_url',
               existing_type=mysql.TEXT(),
               type_=sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.alter_column('hero_image_url',
               existing_type=sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
