"""Add activities table for persistent history

Revision ID: 29673c8836d7
Revises: 0a01c5063dca
Create Date: 2026-04-08 03:27:49.899614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29673c8836d7'
down_revision = '0a01c5063dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('task_title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    # ### end Alembic commands ###
