"""Add BoardMember model and relationships

Revision ID: 935820c94de9
Revises: 0416cc5048fd
Create Date: 2026-04-13 20:33:00.704101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935820c94de9'
down_revision = '0416cc5048fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_members')
    # ### end Alembic commands ###
