"""Added board_members

Revision ID: 949c3f42db05
Revises: 935820c94de9
Create Date: 2026-04-13 21:06:29.692261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '949c3f42db05'
down_revision = '935820c94de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_board_user', ['board_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('board_members_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('board_members_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('board_members_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('board_members_ibfk_1'), 'boards', ['board_id'], ['id'])
        batch_op.drop_constraint('uq_board_user', type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
